# GitPod configuration for OpenCog development environment
image:
  file: .gitpod.Dockerfile

# Port configurations for OpenCog services
ports:
  - port: 17001
    onOpen: ignore
    description: CogServer telnet port
  - port: 18001
    onOpen: ignore  
    description: CogServer web interface
  - port: 5000
    onOpen: ignore
    description: REST API server
  - port: 8080
    onOpen: ignore
    description: Web demos and visualizations

# Workspace initialization tasks
tasks:
  - name: OpenCog Automated Deployment
    init: |
      echo "🧠 Starting OpenCog GitPod Automated Deployment..."
      echo "=================================================="
      
      # Make scripts executable
      chmod +x .gitpod/*.sh
      chmod +x ./setup-opencog-gitpod.sh
      
      # Run environment setup
      echo "🔧 Setting up environment..."
      source .gitpod/setup.sh
      
      # Run main deployment
      echo "🚀 Running automated deployment..."
      .gitpod/deploy.sh
      
      echo "✅ OpenCog environment ready!"
    
    command: |
      # Source the updated environment
      source ~/.bashrc
      
      echo ""
      echo "🧠 OpenCog GitPod Environment Ready!"
      echo "===================================="
      echo ""
      echo "🎯 Quick Start:"
      echo "  opencog_status              - Check environment status"
      echo "  build-opencog              - Build complete OpenCog ecosystem"
      echo "  start-cogserver            - Launch CogServer (port 17001)"
      echo "  start-atomspace-repl       - Launch AtomSpace Guile REPL"
      echo "  demos                      - Show available demos"
      echo "  og                         - Navigate to workspace"
      echo ""
      echo "📖 Documentation:"
      echo "  - Quick Guide: cat .gitpod/README.md"
      echo "  - Troubleshooting: cat .gitpod/TROUBLESHOOTING.md"
      echo "  - OpenCog Wiki: https://wiki.opencog.org/"
      echo ""
      echo "🌐 Service Ports (auto-forwarded by Gitpod):"
      echo "  - CogServer: 17001 (telnet), 18001 (web)"
      echo "  - REST API: 5000"
      echo "  - Web Demos: 8080"
      echo ""
      echo "Happy coding with OpenCog! 🧠✨"

# VS Code extensions useful for OpenCog development
vscode:
  extensions:
    - ms-vscode.cpptools
    - ms-vscode.cmake-tools
    - ms-python.python
    - brettm12345.nixfmt-vscode
    - jnoortheen.nix-ide
    - streetsidesoftware.code-spell-checker

# GitHub integration
github:
  prebuilds:
    # Enable prebuilds for all branches
    master: true
    branches: true
    # Pull requests from the repository
    pullRequests: true
    # Pull requests from forks
    pullRequestsFromForks: true
    # Add a check to PRs 
    addCheck: true
    # Add a "Review in Gitpod" button as a comment to PRs
    addComment: false
    # Add a "Review in Gitpod" button to the PR's description
    addBadge: true

# Workspace options
workspaceLocation: "/workspace/opencog-org"

# Environment variables
env:
  OPENCOG_WORKSPACE: "/workspace/opencog-org"
  PYTHONPATH: "${PYTHONPATH}:/workspace/opencog-org"
  GUILE_LOAD_PATH: "${GUILE_LOAD_PATH}:/workspace/opencog-org"