# GitPod configuration for OpenCog development environment
image:
  file: .gitpod.Dockerfile

# Port configurations for OpenCog services
ports:
  - port: 17001
    onOpen: ignore
    description: CogServer telnet port
  - port: 18001
    onOpen: ignore  
    description: CogServer web interface
  - port: 5000
    onOpen: ignore
    description: REST API server
  - port: 8080
    onOpen: ignore
    description: Web demos and visualizations

# Workspace initialization tasks
tasks:
  - name: OpenCog Environment Setup
    init: |
      echo "🧠 Initializing OpenCog GitPod Environment..."
      
      # Initialize Guix environment
      export PATH="/var/guix/profiles/per-user/gitpod/current-guix/bin:$PATH"
      export GUIX_LOCPATH="$HOME/.guix-profile/lib/locale"
      
      # Create workspace directories
      mkdir -p ~/opencog-workspace
      mkdir -p ~/opencog-build
      
      # Set up environment variables
      echo 'export PATH="/var/guix/profiles/per-user/gitpod/current-guix/bin:$PATH"' >> ~/.bashrc
      echo 'export GUIX_LOCPATH="$HOME/.guix-profile/lib/locale"' >> ~/.bashrc
      echo 'export OPENCOG_BUILD_DIR="$HOME/opencog-build"' >> ~/.bashrc
      echo 'export OPENCOG_WORKSPACE="$HOME/opencog-workspace"' >> ~/.bashrc
      
      # Make setup script executable
      chmod +x ./setup-opencog-gitpod.sh
      
      echo "🎯 Initialization complete! Run ./setup-opencog-gitpod.sh to continue setup."
    
    command: |
      echo "🧠 Welcome to OpenCog GitPod Environment!"
      echo "============================================"
      echo ""
      echo "🚀 Quick Start Commands:"
      echo "  ./setup-opencog-gitpod.sh   - Complete OpenCog environment setup"
      echo "  cd atomspace && mkdir build && cd build && cmake .. && make"
      echo "  cd cogserver && mkdir build && cd build && cmake .. && make"
      echo ""
      echo "📖 Documentation:"
      echo "  - OpenCog: https://opencog.org/"
      echo "  - AtomSpace: https://wiki.opencog.org/w/AtomSpace"
      echo "  - Dependency Build: docs/OPENCOG_DEPENDENCY_BUILD.md"
      echo ""
      echo "🐛 Debugging & Development:"
      echo "  - Guix shell: guix shell gcc-toolchain cmake"
      echo "  - Check dependencies: ldd <binary>"
      echo "  - Logs: journalctl -f"

# VS Code extensions useful for OpenCog development
vscode:
  extensions:
    - ms-vscode.cpptools
    - ms-vscode.cmake-tools
    - ms-python.python
    - brettm12345.nixfmt-vscode
    - jnoortheen.nix-ide
    - streetsidesoftware.code-spell-checker

# GitHub integration
github:
  prebuilds:
    # Enable prebuilds for all branches
    master: true
    branches: true
    # Pull requests from the repository
    pullRequests: true
    # Pull requests from forks
    pullRequestsFromForks: true
    # Add a check to PRs 
    addCheck: true
    # Add a "Review in Gitpod" button as a comment to PRs
    addComment: false
    # Add a "Review in Gitpod" button to the PR's description
    addBadge: true

# Workspace options
workspaceLocation: "/workspace/opencog-org"

# Environment variables
env:
  OPENCOG_WORKSPACE: "/workspace/opencog-org"
  PYTHONPATH: "${PYTHONPATH}:/workspace/opencog-org"
  GUILE_LOAD_PATH: "${GUILE_LOAD_PATH}:/workspace/opencog-org"