# .github/workflows/generate-build-workflow.yml

name: Generate Build Workflow

on:
  push:
    paths:
      - '.github/scripts/generate_build_workflow.js'
      - 'CMakeLists.txt'
      - '*/CMakeLists.txt'
  workflow_dispatch:

jobs:
  generate-workflow:
    name: Generate Generalized Build Workflow
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Generate Build Workflow
        run: |
          cd ${{ github.workspace }}
          node .github/scripts/generate_build_workflow.js

      - name: Check for Changes
        id: changes
        run: |
          if git diff --quiet .github/workflows/ci-org-generalized.yml; then
            echo "changed=false" >> $GITHUB_OUTPUT
          else
            echo "changed=true" >> $GITHUB_OUTPUT
          fi

      - name: Commit and Push Changes
        if: steps.changes.outputs.changed == 'true'
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .github/workflows/ci-org-generalized.yml
          git commit -m "Auto-update generalized build workflow"
          git push